### PR TITLE
Add Electro-Chaff missiles/cloud

### LINKED ISSUE #89: Electro-Chaff Missiles
Add Electro-Chaff Cloud and Electro-Chaff Missiles

### PR DESCRIPTION
**Pull request by Baledin**
Closes #89

### CODE REVIEW

**Comment by philpursglove** [comment]
Not quite sure what to make of this. The Scimitar Sqn bomber is on the obstacle, he's already picked up the Jam token for it, and he didn't get to shoot later. It's hard to tell definitively from this angle but I can't see that there's a line from the First Order Cadet that doesn't pass through the obstacle, so the Scimitar should be rolling an extra defence die. 
image
Is there anything specific we need to specify that the electro-chaff cloud adds a defence die?

**Comment by philpursglove** [comment]
I was going to ask what te red lines are, but from replaying in the 3d view I believe they're where the fuse markers get rendered, can you confirm? 
image

**Comment by Baledin** [comment]
I'll double-check the defense die, the original import had added an extra defense die but in my testing that always worked out to two defense dice being added instead of just one. As far as the red lines, yes it's the fuse marker. I'm not sure why it looks strange in your screenshots, it shows a fuse icon when I test.

**Comment by Baledin** [comment]
In testing, it looks like I was getting Range 3 bonuses or something as I can't replicate what I had been previously seeing. Added the defense die in on obstructed attacks.

**Review by philpursglove — APPROVED** [review]
Retested, looks fine now 😃

**Pull request merged**
