### PR TITLE
81 adon fox battle over endor

### LINKED ISSUE #81: Adon Fox - Battle Over Endor
Add Adon Fox "Battle Over Endor" pilot

image

### PR DESCRIPTION
**Pull request by Baledin**
Closes #81

### CODE REVIEW

**Comment by philpursglove** [comment]
Had a go with this tonight, all seems fine _except_ for the message when he gets an extra defence die, it doesn't show his name
image

**Comment by Baledin** [comment]
I'll double-check it, thanks!

**Comment by Baledin** [comment]
I thought I fixed this earlier, I referenced the PilotName from the HostShip (which I plan to Obsolete because it doesn't do anything currently) instead of the Ship.PilotInfo.PilotName. Fixed it up.

**Comment by philpursglove** [comment]
Yep that's got it
image

**Review by philpursglove — APPROVED** [review]
LGTM

**Pull request merged**
