### PR TITLE
Add Bo-Katan Crew

### LINKED ISSUE #68: Add Bo-Katan Kryze Crew
Add all versions of the Bo-Katan crew upgrade

### PR DESCRIPTION
**Pull request by philpursglove**
Copy in both versions of Bo-Katan from FC Legacy

Republic and Separatist
image
image

Rebel and Scum
image
image

### CODE REVIEW

**Comment by philpursglove** [comment]
Putting this as a draft for now while I have a query on the pricing between the Reps and Seps versions.

**Comment by Baledin** [comment]
What's the question you're asking? I looked at your files and they match the official point releases. Are you comparing to XWA perhaps?

**Comment by philpursglove** [comment]
@Baledin yes, but both YASB and LaunchBayNext have her at 6 points for both factions so I'm not sure when she changed or if AMG snuck a change out

**Comment by Baledin** [comment]
That is strange. I'm guessing that they have it in error that way? I looked at XWA's points and they have 4 & 6 respectively. That said, we should be supporting AMG points only for now, I'm reviewing ways to incorporate different point systems so that the player can ultimately choose but haven't gotten there yet.

Let me know what you find out from YASB and LBN.

**Comment by philpursglove** [comment]
Yep, I think they're wrong. It was that way (8 and 6) in the previous version of the AMG points doc too so let's go with it.

**Review by Baledin — APPROVED** [review]

**Pull request merged**
