### PR TITLE
Add ahsoka crew

### LINKED ISSUE #71: Add Ahsoka Tano Crew
**Is your feature request related to a problem? Please describe.**
Add Ahsoka Tano Crew from FC Legacy

### PR DESCRIPTION
**Pull request by philpursglove**
closes #71 

image
image

### CODE REVIEW

**Comment by philpursglove** [comment]
Is it a bit odd to show the name of the host pilot when the message appears? Should it show 'Ahsoka Tano' instead?

**Comment by Baledin** [comment]
If it makes sense to change it, go ahead. I use HostUpgrade.UpgradeInfo.Name (I think, not looking at the code atm) since it's not directly available to HostUpgrade.

**Comment by Baledin** [comment]
I may have missed something, I think the idea was to have the name of the Upgrade that hosts the effect listed there. I think hard-coding "Ahsoka Tano" was a bad idea (I've worked on plenty of projects with localization so I try to never hardcode anything), but I'm not sure that using the pilotname is better. Sorry for the miscommunication.

**Comment by philpursglove** [comment]
No, that's fair. Localisation isn't something that comes up for me that often so I have a bit of a blind spot on it. 

Also spotted a grammar mistake and fixed it.

**Review by Baledin — APPROVED** [review]

**Pull request merged**
